server:
  port:

spring:
 session:
   store-type: none

 datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.52.77.234:3306/shunfudb?useUnicode=true&characterEncoding=UTF-8
    username: shunfu
    password: colin123!@#

#   mysql 8.0的配置
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shunfudb?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#    username: root
#    password: vergil123

   #   mysql 8.0的配置
#   driver-class-name: com.mysql.cj.jdbc.Driver
#   url: jdbc:mysql://rm-j6c2dj15gqa3mnsqg8o.mysql.rds.aliyuncs.com:3306/shunfudb?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#   username: qq3314097519
#   password: frybre@2912

 jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
# redis:
#      host: 127.0.0.1
#      port: 6379
#      password:
#      timeout: 5000
#      pool:
#        max-idle: 8
#        min-idle: 0
#        max-active: 8
#        max-wait: -1


logging:
  level:
    com.example.demo.dao : debug